name: Generate test matrices pages

# Controls when the action will run.
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'  # This will run every 12 hours
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r pr_matrix/requirements.txt  # Install any necessary dependencies

      # Step 4: Run your extraction code (pr_matrix/pr_matrix.py)
      - name: Extract data
        run: |
          python pr_matrix/generate_test_matrix_data.py

      # Step 5: Commit and push updated JSON to main branch
      - name: Commit and push updated JSON data to main
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
          # Check if there are changes to the JSON file
          git add pr_matrix/output/data.json
          git diff-index --quiet HEAD || git commit -m "Update test matrix data"
          
          # Push the changes to the main branch
          git push origin main

      # Step 6: Run your HTML generation code
      - name: Generate HTML page
        run: |
          python pr_matrix/generate_test_matrix_ui.py

      # Step 7: Deploy the generated HTML page
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages         # The branch the action should deploy to.
          folder: pr_matrix/output  # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}  